stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

services:
  - name: docker:dind
    command: ["--insecure-registry=192.168.104.22"]

before_script:
  - echo $HARBOR_USERNAME
  - echo -n $HARBOR_PASSWORD | docker login $HARBOR_URL -u $HARBOR_USERNAME -p $HARBOR_PASSWORD

build-job:
  stage: build
  script:
    - echo $HARBOR_HOST/$HARBOR_PROJECT/s3-browser
    - docker pull $HARBOR_HOST/$HARBOR_PROJECT/s3-browser:latest || true
    - docker build --pull --cache-from $HARBOR_HOST/$HARBOR_PROJECT/s3-browser:latest --tag $HARBOR_HOST/$HARBOR_PROJECT/s3-browser:latest .

deploy-job:
  stage: deploy
  environment: production
  script:
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/s3-browser:latest
    - echo "Application successfully deployed."

after_script:
  - docker logout $HARBOR_HOST
