[project]
name = "s3-browser"
version = "0.2.3"
description = "Solution for S3 Browser"
readme = "README.md"
authors = [{"name" = "Oktapian Candra"}]
requires-python = ">=3.10.12"
dependencies = [
    "module-typica>=0.2.12",
    "opendal>=0.46.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "pymongo==4.10.1",
    "streamlit>=1.55.0",
    "tomli>=2.4.0",
]


[tool.uv]
package = true

[tool.hatch.build.targets.sdist]
include = ["src"]

[tool.hatch.build.targets.wheel]
include = ["src"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


# ----------------------------------------------------------
#                 RUFF CONFIGURATION
# ----------------------------------------------------------
[tool.ruff]
src = ["src"]

# Linting rule sets
select = [
    "F",    # Pyflakes
    "E",    # Pycodestyle errors
    "W",    # Pycodestyle warnings
    "I",    # Import sorting
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "S",    # flake8-bandit (security)
]

ignore = [
    "E501",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["src"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]      # allow asserts
"__init__.py" = ["F401"]  # allow unused imports


# ----------------------------------------------------------